ripple provider for openlogin adapter
Web3Auth/web3auth-web pull request #1411
Opened 2023-03-17 06:54 UTC by himanshuchawla009

2023-05-12 10:25 UTC, chaitanyapotti commented on packages/providers/xrpl-provider/package.json
> +    "xrpl": "^2.7.0",
make this a peer dependency

2023-05-12 10:25 UTC, chaitanyapotti commented on packages/providers/xrpl-provider/src/providers/privateKeyProviders/interface.ts
> +export type XRPLNetwork = "mainnet" | "testnet" | "devnet";
use const enum

2023-05-18 11:01 UTC, develoQ requested changes
In some places and files it should be xrpl, not ripple.

2023-05-25 09:21 UTC, himanshuchawla009 commented on packages/providers/xrpl-provider/package.json
> +    "xrpl": "^2.7.0",
which one and why?

2023-05-31 03:56 UTC, himanshuchawla009 commented on packages/providers/xrpl-provider/package.json
> +    "xrpl": "^2.7.0",
fixed

2023-05-31 03:56 UTC, himanshuchawla009 commented on packages/providers/xrpl-provider/src/providers/privateKeyProviders/interface.ts
> +export type XRPLNetwork = "mainnet" | "testnet" | "devnet";
fixed

2023-05-31 03:56 UTC, himanshuchawla009 commented on demo/xrpl-react-app /src/services/xrplProvider.ts
> +        method: "ripple_getAccounts"
thanks for the review, fixed all you comments.

2023-05-31 05:08 UTC, develoQ reviewed
The directory name contains spaces.
`web3auth-web/demo/xrpl-react-app `

should be: `web3auth-web/demo/xrpl-react-app`.

2023-06-06 06:11 UTC, merged