Feat/demo mpc mod
Web3Auth/web3auth-web pull request #1439
Opened 2023-04-03 06:17 UTC by arch1995

2023-04-03 09:29 UTC, himanshuchawla009 requested changes

2023-04-03 09:29 UTC, himanshuchawla009 commented on demo/tss-vue-ts-app/src/utils.ts
> +export function getTSSPubKey(dkgPubKey: PointHex, userSharePubKey: PointHex, userTSSIndex: number): any {
get tss pub key directly from tkey sdk, no need of this function with tkey.

2023-04-03 09:34 UTC, himanshuchawla009 requested changes

2023-04-03 09:34 UTC, himanshuchawla009 commented on demo/tss-vue-ts-app/src/App.vue
> +        baseUrl: "http://localhost:3000",
will it work after hosting?

2023-04-03 09:34 UTC, himanshuchawla009 commented on demo/tss-vue-ts-app/src/App.vue
> +    const torusSL = new MockStorageLayer();
we should use metadata server other wise, account wont persist after page reload

2023-04-04 07:43 UTC, arch1995 commented on demo/tss-vue-ts-app/src/App.vue
> +    const torusSL = new MockStorageLayer();
hey, I am saving the device share in local storage, after I refresh and re-login, the account hash is same

2023-04-26 15:38 UTC, merged