Update demos to use latest web3auth packages
Web3Auth/web3auth-web pull request #744
Opened 2022-10-20 08:51 UTC by shahbaz17

2022-10-20 10:00 UTC, yashovardhan commented on demo/auth0-react-app/app/package.json
> +      "safari >= 14"
we need to document this in the docs.

2022-10-20 10:02 UTC, yashovardhan requested changes
The changes are good, can we have readme for each project telling everyone about how to build each demo? Particularly around using lerna bootstrap and nrb before running these demos as well.

Also there should be some explanation around why we have made changes in the package.json - the bigint error.

2022-10-20 15:54 UTC, shahbaz17 commented on demo/auth0-react-app/app/package.json
> +      "safari >= 14"
As discussed. We'll be adding this to a separate troubleshooting page and we can even create a GitHub Discussion around it for now.

2022-10-20 15:55 UTC, shahbaz17 commented
> The changes are good, can we have readme for each project telling everyone about how to build each demo? Particularly around using lerna bootstrap and nrb before running these demos as well.

READMEs updated. 
@yashovardhan

2022-10-21 00:22 UTC, yashovardhan approved these changes
LGTM

2022-10-21 00:54 UTC, chaitanyapotti approved these changes
lgtm

2022-10-21 00:55 UTC, merged